version: 2
jobs:
 build:
  # Variable expansion in working_directory not supported at this time
  # You will need to modify the code below to reflect your github account/repo setup
  working_directory: /go/src/github.com/gsarada/deployer
  docker:
   - image: circleci/golang:1.10
  steps:
   - checkout
   - setup_remote_docker
   - run: 
      name: Setup environment
      command: |
       gb="/src/github.com/${CIRCLE_PROJECT_USERNAME}";
       if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then
         dr="securingdevops"
       else
         dr=$DOCKER_USER
       fi
       cat >> $BASH_ENV << EOF
       export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
       export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
       export DOCKER_REPO="$dr"
       EOF
   - run: mkdir -p "${GOPATH_BASE}"
   - run: mkdir -p "${GOPATH_HEAD}/bin"
   #- run: cp -r ${HOME}/${CIRCLE_PROJECT_REPONAME} ${GOPATH_BASE}/
   - run: go get github.com/govend/govend
   - run: sudo apt-get install awscli    
   - run:
      name: Testing application
      command: |
          go test \
          github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
   - run:
      command: |
         if [ "${CIRCLE_BRANCH}" == "master" ]; then
           docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
           go install --ldflags '-extldflags "-static"' \
           github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
           mkdir bin;
           cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/deployer;
           chmod +x deploymentTests/*;
           docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
         fi
   #- run:
     # name: Run GOVEND to check if outdated dependencies are present
      #command: |
         # cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && \
          #govend -u && git diff --quiet
   - deploy:
       command: |
         if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker images --no-trunc | awk '/^app/ {print $3}' | \
             sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
           docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
           #aws elasticbeanstalk update-environment --region ap-southeast-1 --application-name deployer --environment-id e-k6mykvc5y3 --version-label deployer-api
         fi
